name: app_review
description: Request and Write Reviews and Open Store Listing for Android and iOS in Flutter.
version: 4.3.0
maintainer: Draftea (@drafteame)
repository: https://github.com/fluttercommunity/app_review

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  package_info_plus: ^8.0.1
  url_launcher: ^6.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.appleeducate.appreview
        pluginClass: AppReviewPlugin
      ios:
        pluginClass: AppReviewPlugin
